/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author Asus
 */
public class JajarGenjang_Keliling extends javax.swing.JPanel {

    /**
     * Creates new form JajarGenjang_Keliling
     */
    String datar, miring, hasil;
    public JajarGenjang_Keliling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persegiKelPan1 = new javax.swing.JLabel();
        boxsdatar = new javax.swing.JTextField();
        persegiKelLeb1 = new javax.swing.JLabel();
        boxsmiring = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        persegiKelHas1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(380, 310));
        setLayout(null);

        persegiKelPan1.setText("Sisi Datar");
        add(persegiKelPan1);
        persegiKelPan1.setBounds(30, 20, 80, 14);

        boxsdatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxsdatarActionPerformed(evt);
            }
        });
        boxsdatar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxsdatarKeyTyped(evt);
            }
        });
        add(boxsdatar);
        boxsdatar.setBounds(130, 20, 190, 30);

        persegiKelLeb1.setText("Sisi Miring");
        add(persegiKelLeb1);
        persegiKelLeb1.setBounds(30, 80, 80, 14);

        boxsmiring.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxsmiringKeyTyped(evt);
            }
        });
        add(boxsmiring);
        boxsmiring.setBounds(130, 70, 190, 30);

        jToggleButton3.setText("Hitung");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseReleased(evt);
            }
        });
        add(jToggleButton3);
        jToggleButton3.setBounds(130, 180, 90, 23);

        jToggleButton4.setText("Ulangi");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseReleased(evt);
            }
        });
        add(jToggleButton4);
        jToggleButton4.setBounds(220, 180, 90, 23);

        persegiKelHas1.setText("Keliling");
        add(persegiKelHas1);
        persegiKelHas1.setBounds(30, 230, 70, 14);
        add(jLabel1);
        jLabel1.setBounds(130, 230, 190, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void boxsdatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxsdatarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxsdatarActionPerformed

    private void boxsdatarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxsdatarKeyTyped
        char Input= evt.getKeyChar();
        if(!(Character.isDigit(Input)))
            evt.consume();
    }//GEN-LAST:event_boxsdatarKeyTyped

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        datar = boxsdatar.getText();
        miring = boxsmiring.getText();
        float dtr = Float.parseFloat(datar);
        float mrg = Float.parseFloat(miring);
        float Hsl = 2*(dtr+mrg);
        hasil =String.valueOf(Hsl);
        jLabel1.setText(hasil);
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseReleased
        jToggleButton3.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_jToggleButton3MouseReleased

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        boxsdatar.setText("");
        boxsmiring.setText("");
        jLabel1.setText("");
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseReleased
        jToggleButton4.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_jToggleButton4MouseReleased

    private void boxsmiringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxsmiringKeyTyped
        char Input= evt.getKeyChar();
        if(!(Character.isDigit(Input)))
            evt.consume();
    }//GEN-LAST:event_boxsmiringKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxsdatar;
    private javax.swing.JTextField boxsmiring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel persegiKelHas1;
    private javax.swing.JLabel persegiKelLeb1;
    private javax.swing.JLabel persegiKelPan1;
    // End of variables declaration//GEN-END:variables
}
