/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author Asus
 */
public class Lingkaran_Luas extends javax.swing.JPanel {

    /**
     * Creates new form Lingkaran_Luas
     */
    double phi = 3.14;
    String jari, hasil;
    public Lingkaran_Luas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persegiKelPan1 = new javax.swing.JLabel();
        boxjari = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        persegiKelHas1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(380, 310));
        setLayout(null);

        persegiKelPan1.setText("Jari-Jari");
        add(persegiKelPan1);
        persegiKelPan1.setBounds(40, 40, 80, 14);

        boxjari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxjariActionPerformed(evt);
            }
        });
        boxjari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boxjariKeyTyped(evt);
            }
        });
        add(boxjari);
        boxjari.setBounds(140, 30, 190, 30);

        jToggleButton3.setText("Hitung");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseReleased(evt);
            }
        });
        add(jToggleButton3);
        jToggleButton3.setBounds(140, 160, 90, 23);

        jToggleButton4.setText("Ulangi");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseReleased(evt);
            }
        });
        add(jToggleButton4);
        jToggleButton4.setBounds(240, 160, 90, 23);

        persegiKelHas1.setText("Luas");
        add(persegiKelHas1);
        persegiKelHas1.setBounds(40, 220, 70, 20);
        add(jLabel1);
        jLabel1.setBounds(130, 220, 190, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void boxjariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxjariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxjariActionPerformed

    private void boxjariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxjariKeyTyped
        char Input= evt.getKeyChar();
        if(!(Character.isDigit(Input)))
            evt.consume();
    }//GEN-LAST:event_boxjariKeyTyped

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        jari = boxjari.getText();
        float jr = Float.parseFloat(jari);
        double Hsl = phi*jr*jr;
        hasil =String.valueOf(Hsl);
        jLabel1.setText(hasil);
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseReleased
        jToggleButton3.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_jToggleButton3MouseReleased

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        boxjari.setText("");
        jLabel1.setText("");
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseReleased
        jToggleButton4.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_jToggleButton4MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxjari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel persegiKelHas1;
    private javax.swing.JLabel persegiKelPan1;
    // End of variables declaration//GEN-END:variables
}
